apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: procosys-apps-landing-page
spec: 
  environments:
  - name: dev
    build:
      from: develop
  - name: test
    build:
      from: test
  - name: prod
    build:
      from: main
  components:
  - name: frontend
    ports:
    - name: http
      port: 5000
    publicPort: http
    environmentConfig:
    - environment: prod
      resources:
        requests:
          memory: '256Mi'
          cpu: '100m'
        limits:
          memory: '256Mi'
          cpu: '100m'
