trigger:
  branches:
    include:
    - main

resources:
  repositories:
	  serviceConnection: '${{ variables.nonProdServiceConnection }}'
    containerRegistry: '${{ variables.containerRegistryName }}'
    envGroupName: '$(globalPrefix)-$(fullAppName)-${{ variables.envName }}'
    dockerfilePath: '/.docker/Dockerfile'
    dockerRegistryServiceConnection: '$(dockerRegistryServiceConnectionName)'

  jobs:
    dockerRegistryServiceConnection: '$(dockerRegistryServiceConnectionName)'

# Deploy to Prod
- stage: prod
  displayName: 'Deploy to Prod'
  dependsOn: 'build'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
    envName: 'prod'
    envLabel: 'prod'
    envGroupName: '$(globalPrefix)-$(fullAppName)-${{ variables.envName }}'
    serviceConnection: '${{ variables.prodServiceConnection }}'
    containerRegistry: '${{ variables.containerRegistryName }}'

  jobs:
  # Deploy to AKS
  - template: /src/apps-landing-page/jobs/deploy-aks.yml@templates
    parameters:
      deploymentName: 'deploy_to_k8s'
      dependsOn: ''
      serviceConnection: '${{ variables.serviceConnection }}'
      env: '${{ variables.envName }}'
      envRg: '${{ variables.aksRgName }}'
      envGroup: '${{ variables.envGroupName }}'
      dockerImage: '${{ variables.containerRegistry }}.azurecr.io/${{ variables.repositoryName }}:$(Build.BuildId)'
      clusterName: '${{ variables.aksProdName }}'
      appName: '${{ variables.fullAppName }}'
      replicas: 3